version: '3.4'

services:
  projectx:
    image: projectx
    container_name: projectx
    build: .
    ports:
        - 3000
    networks:
        - web
    labels:
        - "traefik.enable=true" # <== Enable traefik on itself to view whoami and assign subdomain to view it
        - "traefik.http.routers.projectx.entrypoints=web"
        - "traefik.http.routers.projectx.rule=Host(`mainframe.pizzateig.me`)" # <== Setting the domain for the whoami
        - "traefik.http.routers.projectx-web-secured.entrypoints=web-secured"
        - "traefik.http.routers.projectx-web-secured.tls.certresolver=mytlschallenge"
        - "traefik.http.routers.projectx-web-secured.rule=Host(`mainframe.pizzateig.me`)" # <== Setting the domain for the whoami

networks:
  web:
    external: true
