version: "3"

services:
  projectx:
    image: nginx:latest
    container_name: projectx
    ports:
      - 8005
    volumes:
      - ./src:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.projectx.entrypoints=websecure"
      - "traefik.http.routers.projectx.rule=Host(`hive.polychrom.dev`)"
      - "traefik.http.routers.projectx.tls.certresolver=myresolver"
      - "traefik.port=8005"

    networks:
      - traefik_network
networks:
  traefik_network:
    external: true
