version: '2'
services:
  nginx:
    image: nginx:stable
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:mainframe.pizzateig.me"
      - "traefik.port=80"
    restart: always
    networks:
      - web
networks:
  traefik_default:
    external:
      name: web
